In [200]:
import pandas as pd
import utm

In [2]:
pd.set_option('display.precision', 10)

In [3]:
f_name = "validationData"

In [4]:
df = pd.read_csv("uji/raw_data/UJIndoorLoc/data/{}.csv".format(f_name))

In [5]:
df[["LONGITUDE", "LATITUDE"]] = df[["LONGITUDE", "LATITUDE"]]/100000
df

WAP001  WAP002  WAP003  WAP004  WAP005  WAP006  WAP007  WAP008  WAP009  \
0        100     100     100     100     100     100     100     100     100   
1        100     100     100     100     100     100     100     100     100   
2        100     100     100     100     100     100     100     100     100   
3        100     100     100     100     100     100     100     100     100   
4        100     100     100     100     100     100     100     100     100   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1106     100     100     100     100     100     100     100     100     100   
1107     100     100     100     100     100     100     100     100     100   
1108     100     100     100     100     100     100     100     100     100   
1109     100     100     100     100     100     100     100     100     100   
1110     100     100     100     100     100     100     100     100     100   

      WAP010  ...  WAP520     LONGITUDE       LATITUDE  FLOOR  BUILDINGID  \
0        100  ...     100 -0.0751591680  48.6488966292      1           1   
1        100  ...     100 -0.0738386722  48.6483974031      4           2   
2        100  ...     100 -0.0737430208  48.6484653372      4           2   
3        100  ...     100 -0.0736582488  48.6484282925      4           2   
4        100  ...     100 -0.0764149930  48.6492239918      2           0   
...      ...  ...     ...           ...            ...    ...         ...   
1106     100  ...     100 -0.0731734423  48.6479553006      3           2   
1107     100  ...     100 -0.0731373112  48.6479206341      3           2   
1108     100  ...     100 -0.0763753580  48.6490322942      0           0   
1109     100  ...     100 -0.0763665401  48.6490493586      0           0   
1110     100  ...     100 -0.0763794412  48.6490353590      0           0   

      SPACEID  RELATIVEPOSITION  USERID  PHONEID   TIMESTAMP  
0           0                 0       0        0  1380872703  
1           0                 0       0       13  1381155054  
2           0                 0       0       13  1381155095  
3           0                 0       0       13  1381155138  
4           0                 0       0        2  1380877774  
...       ...               ...     ...      ...         ...  
1106        0                 0       0       13  1381156711  
1107        0                 0       0       13  1381156730  
1108        0                 0       0       13  1381247781  
1109        0                 0       0       13  1381247807  
1110        0                 0       0       13  1381247836  

[1111 rows x 529 columns]

In [6]:
df[['x', 'y']] = df.apply(lambda row: pd.Series(utm.from_latlon(row['LATITUDE'], row['LONGITUDE'])[:2]), axis=1)
df

WAP001  WAP002  WAP003  WAP004  WAP005  WAP006  WAP007  WAP008  WAP009  \
0        100     100     100     100     100     100     100     100     100   
1        100     100     100     100     100     100     100     100     100   
2        100     100     100     100     100     100     100     100     100   
3        100     100     100     100     100     100     100     100     100   
4        100     100     100     100     100     100     100     100     100   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1106     100     100     100     100     100     100     100     100     100   
1107     100     100     100     100     100     100     100     100     100   
1108     100     100     100     100     100     100     100     100     100   
1109     100     100     100     100     100     100     100     100     100   
1110     100     100     100     100     100     100     100     100     100   

      WAP010  ...       LATITUDE  FLOOR  BUILDINGID  SPACEID  \
0        100  ...  48.6488966292      1           1        0   
1        100  ...  48.6483974031      4           2        0   
2        100  ...  48.6484653372      4           2        0   
3        100  ...  48.6484282925      4           2        0   
4        100  ...  48.6492239918      2           0        0   
...      ...  ...            ...    ...         ...      ...   
1106     100  ...  48.6479553006      3           2        0   
1107     100  ...  48.6479206341      3           2        0   
1108     100  ...  48.6490322942      0           0        0   
1109     100  ...  48.6490493586      0           0        0   
1110     100  ...  48.6490353590      0           0        0   

      RELATIVEPOSITION  USERID  PHONEID   TIMESTAMP                  x  \
0                    0       0        0  1380872703  715418.0863673664   
1                    0       0       13  1381155054  715517.4607768450   
2                    0       0       13  1381155095  715524.2151945623   
3                    0       0       13  1381155138  715530.6161086694   
4                    0       0        2  1380877774  715324.2086466715   
...                ...     ...      ...         ...                ...   
1106                 0       0       13  1381156711  715568.3366531376   
1107                 0       0       13  1381156730  715571.1453817642   
1108                 0       0       13  1381247781  715327.9442825908   
1109                 0       0       13  1381247807  715328.5209509835   
1110                 0       0       13  1381247836  715327.6305238249   

                     y  
0     5.3925556369e+06  
1     5.3925038835e+06  
2     5.3925117040e+06  
3     5.3925078264e+06  
4     5.3925884737e+06  
...                ...  
1106  5.3924566282e+06  
1107  5.3924528775e+06  
1108  5.3925672803e+06  
1109  5.3925692018e+06  
1110  5.3925676094e+06  

[1111 rows x 531 columns]

In [7]:
df[['x_scaled']] = df[['x']] - df[['x']].mean()
df[['y_scaled']] = df[['y']] - df[['y']].mean()
df

WAP001  WAP002  WAP003  WAP004  WAP005  WAP006  WAP007  WAP008  WAP009  \
0        100     100     100     100     100     100     100     100     100   
1        100     100     100     100     100     100     100     100     100   
2        100     100     100     100     100     100     100     100     100   
3        100     100     100     100     100     100     100     100     100   
4        100     100     100     100     100     100     100     100     100   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1106     100     100     100     100     100     100     100     100     100   
1107     100     100     100     100     100     100     100     100     100   
1108     100     100     100     100     100     100     100     100     100   
1109     100     100     100     100     100     100     100     100     100   
1110     100     100     100     100     100     100     100     100     100   

      WAP010  ...  BUILDINGID  SPACEID  RELATIVEPOSITION  USERID  PHONEID  \
0        100  ...           1        0                 0       0        0   
1        100  ...           2        0                 0       0       13   
2        100  ...           2        0                 0       0       13   
3        100  ...           2        0                 0       0       13   
4        100  ...           0        0                 0       0        2   
...      ...  ...         ...      ...               ...     ...      ...   
1106     100  ...           2        0                 0       0       13   
1107     100  ...           2        0                 0       0       13   
1108     100  ...           0        0                 0       0       13   
1109     100  ...           0        0                 0       0       13   
1110     100  ...           0        0                 0       0       13   

       TIMESTAMP                  x                 y        x_scaled  \
0     1380872703  715418.0863673664  5.3925556369e+06   10.3020326978   
1     1381155054  715517.4607768450  5.3925038835e+06  109.6764421765   
2     1381155095  715524.2151945623  5.3925117040e+06  116.4308598938   
3     1381155138  715530.6161086694  5.3925078264e+06  122.8317740009   
4     1380877774  715324.2086466715  5.3925884737e+06  -83.5756879970   
...          ...                ...               ...             ...   
1106  1381156711  715568.3366531376  5.3924566282e+06  160.5523184690   
1107  1381156730  715571.1453817642  5.3924528775e+06  163.3610470956   
1108  1381247781  715327.9442825908  5.3925672803e+06  -79.8400520778   
1109  1381247807  715328.5209509835  5.3925692018e+06  -79.2633836850   
1110  1381247836  715327.6305238249  5.3925676094e+06  -80.1538108436   

            y_scaled  
0     -13.2564718071  
1     -65.0099246185  
2     -57.1894201143  
3     -61.0670114774  
4      19.5803346680  
...              ...  
1106 -112.2652259991  
1107 -116.0159377353  
1108   -1.6130568022  
1109    0.3083773721  
1110   -1.2839678898  

[1111 rows x 533 columns]

In [8]:
df.to_csv("{}.csv".format(f_name))

In [1]:
import torch

/home/rahul/grape/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [99]:
def get_known_mask(known_prob, edge_num):
    known_mask = (torch.FloatTensor(edge_num, 1).uniform_() < known_prob).view(-1)
    return known_mask

In [101]:
get_known_mask(0.7, 10)

tensor([False,  True,  True, False,  True,  True, False, False,  True,  True])

In [97]:
def get_known_mask_new(known_prob, edge_num, shape):
    left = torch.ones(shape[0], shape[1]-2).bool()
    right = torch.FloatTensor(shape[0], 1).uniform_() < known_prob
    right = torch.cat((right, right), dim=1)
    known_mask = (torch.cat((left, right), dim=1))
    print(known_mask)
    return known_mask.view(-1)

In [98]:
get_known_mask_new(0.5, 5, (4,3))

tensor([[ True,  True,  True],
        [ True, False, False],
        [ True,  True,  True],
        [ True,  True,  True]])


tensor([ True,  True,  True,  True, False, False,  True,  True,  True,  True,
         True,  True])

In [13]:
import pickle

In [287]:
with open('/home/rahul/data/GRAPE/uji/test/UJIndoorLoc/y101/result.pkl', 'rb') as f:
    obj = pickle.load(f)

In [288]:
obj.keys()

dict_keys(['args', 'outputs', 'curves', 'lr', 'test_edge_mask'])

In [198]:
torch.tensor(obj["outputs"]["best_valid_l1_pred_test"]).view(-1, 2)

tensor([[0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1061, 0.1086],
        [0.1

In [272]:
df = pd.DataFrame(obj['filled_data'], columns=df_X.columns)

In [291]:
obj["test_edge_mask"].view(-1, 522)

tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False,  True,  True],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]])

In [293]:
mask = obj["test_edge_mask"].view(-1, 522)[:, -1]

In [300]:
sum(mask.numpy())

304

In [298]:
df[~mask.numpy()]

WAP001  WAP002  WAP003  WAP004  ...  WAP519  WAP520   x_scaled   y_scaled
0        0.0     0.0     0.0     0.0  ...     0.0     0.0   7.732547 -22.384821
1        0.0     0.0     0.0     0.0  ...     0.0     0.0   2.765043 -57.899269
2        0.0     0.0     0.0     0.0  ...     0.0     0.0   8.863330 -45.482925
3        0.0     0.0     0.0     0.0  ...     0.0     0.0   0.838918 -63.934357
4        0.0     0.0     0.0     0.0  ...     0.0     0.0  24.442493 -11.102702
...      ...     ...     ...     ...  ...     ...     ...        ...        ...
1476     0.0     0.0     0.0     0.0  ...     0.0     0.0  21.034941  -8.544110
1477     0.0     0.0     0.0     0.0  ...     0.0     0.0   2.765043 -57.899269
1479     0.0     0.0     0.0     0.0  ...     0.0     0.0  -1.710542  -9.975412
1482     0.0     0.0     0.0     0.0  ...     0.0     0.0   2.765043 -57.899269
1483     0.0     0.0     0.0     0.0  ...     0.0     0.0  -1.250173  -9.133550

[1180 rows x 522 columns]

In [306]:
df_train = pd.read_csv('/home/rahul/data/GRAPE/uji/raw_data/UJIndoorLoc/data/trainingData.csv')

In [303]:
with open('/home/rahul/data/GRAPE/uji/test/UJIndoorLoc/missing_0.2/feat_imp/result.pkl', 'rb') as f:
    obj = pickle.load(f)

In [308]:
mask = obj["train_edge_mask"].view(-1, 522)[:, -1]
len(mask)

1484

In [311]:
floor= 1

df_train = df_train.loc[df_train['FLOOR'] == floor]

In [312]:
df_train

WAP001  WAP002  WAP003  ...             y    x_scaled    y_scaled
3304        0       0       0  ...  5.392516e+06    7.732547  -22.384822
3305        0       0       0  ...  5.392480e+06    2.765043  -57.899268
3306        0       0       0  ...  5.392492e+06    8.863330  -45.482925
3307        0       0       0  ...  5.392474e+06    0.838918  -63.934355
3308        0       0       0  ...  5.392527e+06   24.442493  -11.102702
...       ...     ...     ...  ...           ...         ...         ...
19926       0       0       0  ...  5.392425e+06  104.773938 -112.577931
19927       0       0       0  ...  5.392498e+06   58.279677  -39.494729
19928       0       0       0  ...  5.392426e+06  104.766420 -111.751678
19931       0       0       0  ...  5.392500e+06   55.368869  -37.503215
19933       0       0       0  ...  5.392500e+06   58.320177  -38.357098

[5002 rows x 533 columns]

In [313]:
df_train = df_train[mask.numpy()]

ValueError: Item wrong length 1484 instead of 5002.

In [220]:
df = pd.read_csv('uji/raw_data/UJIndoorLoc/data/trainingData.csv', dtype=float)
# df = pd.concat([df_train, df_val])

building_id = 1
floor= 1

df = df.loc[df['BUILDINGID'] == building_id]
df = df.loc[df['FLOOR'] == floor]

df_X = df.iloc[: , 0:520]
df_y = df[['x_scaled', 'y_scaled']]

df_X[['x_scaled', 'y_scaled']] = df_y

/tmp/ipykernel_445438/523757729.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_X[['x_scaled', 'y_scaled']] = df_y
/tmp/ipykernel_445438/523757729.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_X[['x_scaled', 'y_scaled']] = df_y


In [268]:
df_X

WAP001  WAP002  WAP003  WAP004  ...  WAP519  WAP520   x_scaled   y_scaled
3304      0.0     0.0     0.0     0.0  ...     0.0     0.0   7.732547 -22.384822
3305      0.0     0.0     0.0     0.0  ...     0.0     0.0   2.765043 -57.899268
3306      0.0     0.0     0.0     0.0  ...     0.0     0.0   8.863330 -45.482925
3307      0.0     0.0     0.0     0.0  ...     0.0     0.0   0.838918 -63.934355
3308      0.0     0.0     0.0     0.0  ...     0.0     0.0  24.442493 -11.102702
...       ...     ...     ...     ...  ...     ...     ...        ...        ...
15716     0.0     0.0     0.0     0.0  ...     0.0     0.0  -1.710542  -9.975413
15717     0.0     0.0     0.0     0.0  ...     0.0     0.0   9.764951 -63.337842
15718     0.0     0.0     0.0     0.0  ...     0.0     0.0   0.838918 -63.934355
15719     0.0     0.0     0.0     0.0  ...     0.0     0.0   2.765043 -57.899268
15724     0.0     0.0     0.0     0.0  ...     0.0     0.0  -1.250173  -9.133550

[1484 rows x 522 columns]

In [253]:
a = df[["WAP511", "x_scaled","y_scaled"]]

In [254]:
b = df_X[["WAP511", "x_scaled","y_scaled"]]

In [257]:
c = df-df_X

In [259]:
df.head(50)

WAP001  WAP002  WAP003  WAP004  ...  WAP519  WAP520   x_scaled   y_scaled
3304     0.0     0.0     0.0     0.0  ...     0.0     0.0   7.732547 -22.384821
3305     0.0     0.0     0.0     0.0  ...     0.0     0.0   2.765043 -57.899269
3306     0.0     0.0     0.0     0.0  ...     0.0     0.0   8.863330 -45.482925
3307     0.0     0.0     0.0     0.0  ...     0.0     0.0   0.838918 -63.934357
3308     0.0     0.0     0.0     0.0  ...     0.0     0.0  24.442493 -11.102702
3309     0.0     0.0     0.0     0.0  ...     0.0     0.0   9.764951 -63.337841
3310     0.0     0.0     0.0     0.0  ...     0.0     0.0  30.934044   1.860124
3311     0.0     0.0     0.0     0.0  ...     0.0     0.0  -0.255031  24.077023
3312     0.0     0.0     0.0     0.0  ...     0.0     0.0  12.571095 -48.336315
3313     0.0     0.0     0.0     0.0  ...     0.0     0.0  36.093906  24.207418
3314     0.0     0.0     0.0     0.0  ...     0.0     0.0  38.499203  11.213067
3315     0.0     0.0     0.0     0.0  ...     0.0     0.0  42.570648  24.321367
3316     0.0     0.0     0.0     0.0  ...     0.0     0.0  32.654762   6.994245
3317     0.0     0.0     0.0     0.0  ...     0.0     0.0  32.482330  26.903538
3318     0.0     0.0     0.0     0.0  ...     0.0     0.0  23.792734   7.175596
3319     0.0     0.0     0.0     0.0  ...     0.0     0.0  28.586918  35.158497
3320     0.0     0.0     0.0     0.0  ...     0.0     0.0  25.508617  12.804941
3321     0.0     0.0     0.0     0.0  ...     0.0     0.0  -0.192444  21.330946
3324     0.0     0.0     0.0     0.0  ...     0.0     0.0  21.034941  -8.544110
3441     0.0     0.0     0.0     0.0  ...     0.0     0.0   7.732547 -22.384821
3442     0.0     0.0     0.0     0.0  ...     0.0     0.0   0.838918 -63.934357
3443     0.0     0.0     0.0     0.0  ...     0.0     0.0  -0.246883  23.319345
3444     0.0     0.0     0.0     0.0  ...     0.0     0.0   8.863330 -45.482925
3445     0.0     0.0     0.0     0.0  ...     0.0     0.0  -0.251236  23.734177
3446     0.0     0.0     0.0     0.0  ...     0.0     0.0  24.442493 -11.102702
3447     0.0     0.0     0.0     0.0  ...     0.0     0.0  30.934044   1.860124
3448     0.0     0.0     0.0     0.0  ...     0.0     0.0  -0.224893  22.257055
3449     0.0     0.0     0.0     0.0  ...     0.0     0.0  12.571095 -48.336315
3450     0.0     0.0     0.0     0.0  ...     0.0     0.0   9.764951 -63.337841
3451     0.0     0.0     0.0     0.0  ...     0.0     0.0  36.093906  24.207418
3452     0.0     0.0     0.0     0.0  ...     0.0     0.0  42.570648  24.321367
3453     0.0     0.0     0.0     0.0  ...     0.0     0.0  -0.215062  21.983009
3454     0.0     0.0     0.0     0.0  ...     0.0     0.0  32.482330  26.903538
3455     0.0     0.0     0.0     0.0  ...     0.0     0.0  23.792734   7.175596
3456     0.0     0.0     0.0     0.0  ...     0.0     0.0  21.034941  -8.544110
3457     0.0     0.0     0.0     0.0  ...     0.0     0.0  28.586918  35.158497
3458     0.0     0.0     0.0     0.0  ...     0.0     0.0  25.508617  12.804941
3459     0.0     0.0     0.0     0.0  ...     0.0     0.0  -0.193481  21.357899
3580     0.0     0.0     0.0     0.0  ...     0.0     0.0   2.765043 -57.899269
3581     0.0     0.0     0.0     0.0  ...     0.0     0.0   0.838918 -63.934357
3582     0.0     0.0     0.0     0.0  ...     0.0     0.0   8.863330 -45.482925
3584     0.0     0.0     0.0     0.0  ...     0.0     0.0   7.732547 -22.384821
3585     0.0     0.0     0.0     0.0  ...     0.0     0.0   9.764951 -63.337841
3586     0.0     0.0     0.0     0.0  ...     0.0     0.0  12.571095 -48.336315
3587     0.0     0.0     0.0     0.0  ...     0.0     0.0   7.770562 -69.264023
3588     0.0     0.0     0.0     0.0  ...     0.0     0.0  24.442493 -11.102702
3589     0.0     0.0     0.0     0.0  ...     0.0     0.0  -0.218666  22.083717
3590     0.0     0.0     0.0     0.0  ...     0.0     0.0  42.570648  24.321367
3591     0.0     0.0     0.0     0.0  ...     0.0     0.0  38.499203  11.213067
3592  

In [314]:
[1,2,3,4,5][-2:]

[4, 5]

In [260]:
obj["test_edge_mask"].view(-1, 522)[5:10]

KeyError: 'test_edge_mask'

In [174]:
vals = obj["test_edge_mask"].float().clone()
vals[obj["test_edge_mask"]] = torch.tensor(obj["outputs"]["best_valid_l1_pred_test"])

In [175]:
vals.shape

torch.Size([774648])

In [176]:
vals

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [192]:
import torch

# Create a boolean tensor
x = torch.tensor([True, False, True, False])
y = torch.tensor([1, 2, 3, 4])

replacement_values = [5, 6]

y[x] = torch.tensor(replacement_values)

y

tensor([5, 2, 6, 4])

In [191]:
y[x]

tensor([5, 6])

In [170]:
y

tensor([ True,  True,  True, False])

In [45]:
from uji.uji_data_mdi import create_edge, create_node, create_edge_attr
import pandas as pd

In [48]:
data = {'name': [5, 6, 7, 8],
        'age': [25, 30, 35, 40],
        'city': [6, 9, 8, 5]}

# create the DataFrame
df = pd.DataFrame(data)

In [49]:
df

name  age  city
0     5   25     6
1     6   30     9
2     7   35     8
3     8   40     5

In [50]:
create_edge(df)

([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6],
 [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [51]:
create_node(df, 1)

[[1.0, 0.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0]]

In [58]:
edge_attr = torch.tensor(create_edge_attr(df), dtype=torch.float)
edge_attr.shape[0]

24

In [54]:
edge_start, edge_end = create_edge(df)
edge_index = torch.tensor([edge_start, edge_end], dtype=int)

In [77]:
edge_index.view(-1)

tensor([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6,
        4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [79]:
edge_attr.view(-1)

tensor([ 5., 25.,  6.,  6., 30.,  9.,  7., 35.,  8.,  8., 40.,  5.,  5., 25.,
         6.,  6., 30.,  9.,  7., 35.,  8.,  8., 40.,  5.])

In [66]:
edge_attr

tensor([[ 5.],
        [25.],
        [ 6.],
        [ 6.],
        [30.],
        [ 9.],
        [ 7.],
        [35.],
        [ 8.],
        [ 8.],
        [40.],
        [ 5.],
        [ 5.],
        [25.],
        [ 6.],
        [ 6.],
        [30.],
        [ 9.],
        [ 7.],
        [35.],
        [ 8.],
        [ 8.],
        [40.],
        [ 5.]])

In [81]:
df_ten = torch.tensor(df.values)

In [82]:
df_ten

tensor([[ 5, 25,  6],
        [ 6, 30,  9],
        [ 7, 35,  8],
        [ 8, 40,  5]])

In [84]:
df_ten.reshape(-1)

tensor([ 5, 25,  6,  6, 30,  9,  7, 35,  8,  8, 40,  5])

In [110]:
l1 = torch.mean(torch.linalg.norm(torch.tensor([[0, 3]]) - torch.tensor([[1, 2]]), 2, dim=1))

RuntimeError: linalg.vector_norm: Expected a floating point or complex tensor as input. Got Long

In [284]:
torch.BoolTensor([True]*(10-3) + [False]*3).view(-1)

tensor([ True,  True,  True,  True,  True,  True,  True, False, False, False])

In [280]:
[True]*(10-3) + [False]*3

[True, True, True, True, True, True, True, False, False, False]

In [301]:
unlab_train = 0.2
log_dir = f"missing_{unlab_train}"

In [302]:
log_dir

'missing_0.2'

In [315]:
train_mask = get_known_mask_val(_, y.shape[0], test_num)

NameError: name 'get_known_mask_val' is not defined

In [316]:
from utils.utils import get_known_mask_val

ImportError: cannot import name 'get_known_mask_val' from 'utils.utils' (/home/rahul/data/GRAPE/utils/utils.py)

In [318]:
~[True, False]

TypeError: bad operand type for unary ~: 'list'

In [322]:
!w

 00:50:45 up 9 days, 12:30,  3 users,  load average: 1.54, 1.26, 1.45
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
rahul    pts/15   10.0.2.25        Fri21    2days 20.57s  0.01s www-browser fil
rahul    pts/32   10.0.2.25        Fri22    1:22   0.06s  0.06s -bash
aritra   pts/77   tmux(2395436).%0 23:51   58:37   2:58   0.00s sh -c ./nerdss 


In [323]:
!nvidia-smi

Mon Mar 27 00:50:47 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:01:00.0 Off |                  Off |
| 45%   62C    P8    25W / 300W |   2308MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------